{% set name = "jupyterlab-urdf" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-robotics/{{ name }}/releases/download/v{{ version }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: a0ef3f50e70ab5d234b04b2a48d9c23ea6d42928b827a748712803b9aeab1ecd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - nodejs
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_urdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-robotics/jupyterlab-urdf
  summary: A URDF viewer and editor extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IsabelParedes
